### ISSUE TITLE
UI KIT

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#1]
Количество элементов их расположение должно соответствовать макету UI KIT + pixelperfect.
Ripple эффект на кнопке в месте нажатия посмотри по макету.
Посмотри как выглядит DROP DOWN - OPEN у списка.

**Comment by whiteGloom** [comment]
Ну, я по правил, вроде..
Единственное — различия в местах, где в макете разные отступы и searchbar один.

**Comment by EvgeniyChuprov** [comment]
Пиксель перфекту должен соответствовать весь макет включая отступы от заголовков до элементов, расстояния между элементами и текстового содержания элементов на остальных страницах ставишь свои.

**Comment by whiteGloom** [comment]
Ок. Картинки менять?

**Comment by EvgeniyChuprov** [comment]
Не уверен что обязательно, но на всякий случай лучше поменяй.

**Comment by whiteGloom** [comment]
Хорошо.

**Comment by whiteGloom** [comment]
Ну, вроде, подогнал под pixel-perfect, обновил содержимое.
