### ISSUE TITLE
CONTACTS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#2]
Странное поведение карты.
![Peek 2019-11-19 1349](https://user-images.githubusercontent.com/36810364/69140509-b0def380-0ad3-11ea-91bb-296e6670967b.gif)

**Comment by whiteGloom** [comment]
Вроде, пофиксил.

**Comment by EvgeniyChuprov** [comment]
У меня проблема осталась, что на gitpage, что в проекте

**Comment by whiteGloom** [comment]
Вы про "При загрузке Google Карт возникла ошибка" или про то, что она не загружается с первого раза?

**Comment by EvgeniyChuprov** [comment]
все тоже самое что на гифке, без изменений.

**Comment by whiteGloom** [comment]
Понял.

**Comment by whiteGloom** [comment]
А сейчас?

**Comment by EvgeniyChuprov** [comment]
Вроде норм.
