### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#3]
Переписать js на классы ES6.
Код должен соответствовать стандартам fsd и AirBnB,  не использовать var, ++ и т.д. Лучше поставить ESlint и настроить его на правила AirBnB.

**Comment by whiteGloom** [comment]
Мех.. Я, просто, не особо парился по js, так как макет был не про это.. Ладно, перепишу.

**Comment by whiteGloom** [comment]
Кстати, насколько я понял, ++ запрещены для того, что бы люди не путали в программах i++ и ++i?

**Comment by EvgeniyChuprov** [comment]
Остались миксины  в которых js выполнен не на классах.

**Comment by EvgeniyChuprov** [comment]
Минимизировать constructor у классов.
Частные методы обозначить префиксом "_"

**Comment by EvgeniyChuprov** [comment]
1. calendar не на классе.
2. Конструктор класса должен быть максимально легковесным.
Тут и в других классах методы из конструктора вынести в отдельный метод и использовать его.
![Снимок экрана от 2019-12-14 09-14-57](https://user-images.githubusercontent.com/36810364/70844448-3dba6a00-1e52-11ea-9402-846f7863a40e.png)

**Comment by whiteGloom** [comment]
https://github.com/whiteGloom/Response-for-task-2_2/commit/da126f9c9b3a380126e789b877d0b91df7f29c56
