### ISSUE TITLE
pixel perfect

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#4]
Проверить по всему макету. Расширение pixel perfect для браузера установил?
![image](https://user-images.githubusercontent.com/36810364/69417497-d2d1b380-0d29-11ea-86ce-7b4eaa701cf9.png)

**Comment by whiteGloom** [comment]
Да, стоит.

**Comment by EvgeniyChuprov** [comment]
Не совпадает ни текст, ни элементы.
![Снимок экрана от 2019-12-11 18-12-55](https://user-images.githubusercontent.com/36810364/70633684-f9587f80-1c41-11ea-9955-f390e220f9cc.png)

**Comment by whiteGloom** [comment]
![изображение](https://user-images.githubusercontent.com/36995502/70634032-18680900-1c64-11ea-96b9-5a30c8abc7e2.png)
Разница в +/- 1-2 пикселя в худшем случае.
С текстом я ничего не поделаю — не совпадает сам шрифт. Гонять его размеры можно до бесконечности, но к полному соответсвию я его не приведу, т.к. его размер меняется даже от его расширения.
Есть элементы, которые отличаются от макета, но скриншот явно неудачный, т.к. половина несоответствий из-за того, что трафарет криво приложен. То что сильно режет глаз — поправлю.
