### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#5]
Имя миксина должно совпадать с именем блока. Проверить во всем проекте.
![image](https://user-images.githubusercontent.com/36810364/69418818-745a0480-0d2c-11ea-990e-c255811129d6.png)

**Comment by whiteGloom** [comment]
То есть использовать миксины как паки-настроек всё-таки нельзя? Это, ведь, не совсем блоки..

Для каждого немного-различающегося блока нужно делать специфичный блок обёртку, несмотря на одинаковые стили, семантику и построение?

**Comment by whiteGloom** [comment]
Я перепишу, мне не сложно. Просто хотелось уточнить - в первом макете я сделал так же, но замечаний это, вроде как не вызвало.. И если все-таки нельзя, то нужно будет исправить и там.
Кстати, я завтра буду только вечером.

**Comment by EvgeniyChuprov** [comment]
Видимо пропустил несоответствия названий. Да нужно везде  поправить.

**Comment by whiteGloom** [comment]
Ну, вроде, поправил. Сейчас перенесу правку в первым макет.

**Comment by EvgeniyChuprov** [comment]
На начальной странице должен быть один общий блок. Проверь на всех страницах.
![Снимок экрана от 2019-11-25 07-12-53](https://user-images.githubusercontent.com/36810364/69511933-1bb88080-0f53-11ea-9d01-ebc8650ca52f.png)

**Comment by EvgeniyChuprov** [comment]
Не соответствие миксина и класса. Вся папка content такая, возможно где то еще.
![Снимок экрана от 2019-11-28 06-52-48](https://user-images.githubusercontent.com/36810364/69776115-fffbe700-11ab-11ea-9128-50452e683e6f.png)

**Comment by EvgeniyChuprov** [comment]
Дать блоку +р осмысленное название.
