### ISSUE TITLE
Разные замечания

### ISSUE THREAD

**Issue by EvgeniyChuprov** [whiteGloom/Response-for-task-2_2#6]
Масштабируемость. Проверить с остальными элементами.
![image](https://user-images.githubusercontent.com/36810364/69510931-b6af5b80-0f4f-11ea-8b22-71ccbf6899db.png)
Файл стилей свой блок потерял.
![файл стилей потерял свой блок](https://user-images.githubusercontent.com/36810364/69511083-29203b80-0f50-11ea-98c7-2e4811535743.png)

Плагины нужно подключать через webpack
![Снимок экрана от 2019-11-25 06-55-30](https://user-images.githubusercontent.com/36810364/69511278-a481ed00-0f50-11ea-8ac0-3d3dad271770.png)

Рекомендую установить расширение Code Spell Checker для проверки грамматики.
![Снимок экрана от 2019-11-25 07-10-21](https://user-images.githubusercontent.com/36810364/69511823-b6fd2600-0f52-11ea-890d-8fec28bb470d.png)

и ESlint для проверки стандартов
![Снимок экрана от 2019-11-25 07-09-32](https://user-images.githubusercontent.com/36810364/69511786-9c2ab180-0f52-11ea-83ea-fb861391e673.png)

**Comment by whiteGloom** [comment]
Что делать, если плагин нельзя скачать через npm?

**Comment by EvgeniyChuprov** [comment]
> Что делать, если плагин нельзя скачать через npm?

Это который? По идее искать аналоги либо реализовывать самому. Если на самом деле нету, то уточню.

**Comment by whiteGloom** [comment]
Да просто плагин "perfect-timepicker" (файл `jquery.datetimepicker.js`) нельзя скачать через npm. Он не npm модуль и даже через github его не скачать, т.к. автор практически не заполнял package.json.
Ладно, что-нибудь придумаю.

**Comment by EvgeniyChuprov** [comment]
Этот?
![image](https://user-images.githubusercontent.com/36810364/69519806-f97f2c80-0f6b-11ea-8659-15293ea74425.png)

А так в jqueryUI и ползунки и календари есть.

**Comment by whiteGloom** [comment]
Оставшиеся правки в js и плагинах сделаю завтра.

**Comment by whiteGloom** [comment]
Всё бы хорошо, но я не понимаю, как обойтись без анонимных функций в ситуациях, когда важен контекст в колбеке.. Например, метод `each` в jQuery — он принимает колбек-функцию, в качестве контекста которой указывает элемент. 

![изображение](https://user-images.githubusercontent.com/36995502/69646990-53324480-109b-11ea-951a-ccd0a01367ee.png)

Что делать? Для каждого элемента указывать отдельную обрабатывающую функцию? Или я неправильно понял правило func-names?

**Comment by EvgeniyChuprov** [comment]
1. Блок chart - длина строк.
2. Зачем js-tick если в блоке нет js-кода?
![Снимок экрана от 2019-12-11 18-08-08](https://user-images.githubusercontent.com/36810364/70633215-3a03c900-1c41-11ea-8000-8fbafea80abc.png)
3. blog-block не все миксины подключены. #
