### ISSUE TITLE
Абстрагировать JS в блоках

### ISSUE THREAD

**Issue by Znack** [whiteGloom/Response-for-task-2_2#7]
Надо чтобы весь код блока был по максимуму в папке этого блока, включая скрипты на js. Например, сейчас инициация календаря происходит вообще в левом месте. Если я захочу что-то поправить, мне придется по всему проекту искать место, куда вносить правки. А по хорошему я в той же папке мог бы открыть js файл и там найти всё нужное :)

**Comment by Znack** [comment]
А код вне блоков должен вообще не знать по максимуму ничего о содержимом блоков. Сейчас же получается, что `scripts/scripts.js` знает о внутреннем устройстве кучи блоков, включая какие там HTML-классы используются :(

**Comment by whiteGloom** [comment]
Тогда получается, данные через data- передавать?

**Comment by Znack** [comment]
Смотря какие, откуда, куда и зачем

**Comment by whiteGloom** [comment]
Ок, поправлю.
